### ISSUE TITLE
Please fix the docs

### ISSUE THREAD

**Issue by andrewfluck** [Arthelon/spf-express#1]
The documentation for this is **horrible**, can you write a better one, maybe even make an example in this repo so I could better understand how this works. This is just what I need, I just don't understand how to use it. Thank you 😄

**Comment by Arthelon** [comment]
The examples used assumed a basic understanding over the SPF framework. I've updated the readme to make things a bit clearer. Hope it helps.

**Comment by andrewfluck** [comment]
I get SPF, I'm using it on the client side and it works fine, I guess I should have described it better but, It just doesn't work in the same way. Could you provide a working example? I would really appreciate that.

**Comment by andrewfluck** [comment]
By working example I mean just in another folder or branch just make a server with the module inside it just to see how it works.

**Comment by Arthelon** [comment]
whipped together a really basic example, you are free to work on it if you want.

**Comment by andrewfluck** [comment]
Thank you I will check it out

**Comment by andrewfluck** [comment]
Gonna modify it to use a templating engine, see if it works
