### ISSUE TITLE
No support for URL params in express middleware functions

### ISSUE THREAD

**Issue by andrewfluck** [Arthelon/spf-express#4]
If I do something like

``` js
paths: {
    '/weather/:zip': (req, res, next) {
        res.json({
            body: {
                content: ejs.renderFile('./views/partials/weather.ejs', {
                    title: `Weather (${req.params.zip})`
                }, (err, str) => {
                    if (err) return err;
                    return `${str}`;
                })
            }
        })
    }
}
```

It will redirect as normal instead of replacing content.
Same story for query strings.
@Arthelon please fix.

**Comment by andrewfluck** [comment]
I actually really need this since I am (as content hints to) overhauling a weather project to use this library and replace content as partials

**Comment by Arthelon** [comment]
Added support for URL params. Tell me if you bump into any issues.

**Comment by andrewfluck** [comment]
Thank you! I will test it out when I get home.

**Comment by andrewfluck** [comment]
@Arthelon everything works as it should. You should probably update the repository on npm.
